/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef RSKELETALMESHEX_API
#define RSKELETALMESHEX_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern RSKELETALMESHEX_API FName RSKELETALMESHEX_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class RSKELETALMESHEX_API ARSkeletalActor : public AActor
{
public:
    BITFIELD bUpdateRotation:1 GCC_PACK(4);
    BITFIELD bDisableNativeUpdate:1;
    FRotator RotationOffset GCC_PACK(4);
    FVector LocationOffset;
    class AActor* AttachedTarget;
    INT BoneIndex;
    DECLARE_FUNCTION(execDetachFromBone);
    DECLARE_FUNCTION(execUpdateAttached);
    DECLARE_FUNCTION(execAttachToBone);
    DECLARE_CLASS(ARSkeletalActor,AActor,0,RSkeletalMeshEx)
    #include "ARSkeletalActor.h"
};


class RSKELETALMESHEX_API URSkeletalMeshEx : public UObject
{
public:
    DECLARE_FUNCTION(execGetBoneRotationByIndex);
    DECLARE_FUNCTION(execGetBoneLocationByIndex);
    DECLARE_FUNCTION(execGetBoneIndex);
    DECLARE_FUNCTION(execGetBoneNameByIndex);
    DECLARE_FUNCTION(execGetNumBones);
    DECLARE_FUNCTION(execBoneExists);
    DECLARE_FUNCTION(execGetBoneRotation);
    DECLARE_FUNCTION(execGetBoneLocation);
    DECLARE_FUNCTION(execGetBoneDetails);
    DECLARE_CLASS(URSkeletalMeshEx,UObject,0,RSkeletalMeshEx)
    NO_DEFAULT_CONSTRUCTOR(URSkeletalMeshEx)
};

#endif

AUTOGENERATE_FUNCTION(ARSkeletalActor,-1,execDetachFromBone);
AUTOGENERATE_FUNCTION(ARSkeletalActor,-1,execUpdateAttached);
AUTOGENERATE_FUNCTION(ARSkeletalActor,-1,execAttachToBone);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneRotationByIndex);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneLocationByIndex);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneIndex);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneNameByIndex);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetNumBones);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execBoneExists);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneRotation);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneLocation);
AUTOGENERATE_FUNCTION(URSkeletalMeshEx,-1,execGetBoneDetails);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
