/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef RVMP3PLAYER_API
#define RVMP3PLAYER_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern RVMP3PLAYER_API FName RVMP3PLAYER_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(AddSlashes)
AUTOGENERATE_NAME(ReadPlaylist)

#ifndef NAMES_ONLY


struct ARMp3Player_eventReadPlaylist_Parms
{
};
struct ARMp3Player_eventAddSlashes_Parms
{
    FString sourcestring;
    FString ReturnValue;
};
class RVMP3PLAYER_API ARMp3Player : public AActor
{
public:
    FStringNoInit Directory;
    INT MusicVolume;
    BITFIELD bWasInitialized:1 GCC_PACK(4);
    class APlayerPawn* PP GCC_PACK(4);
    class ALevelInfo* CurLevel;
    class ALevelInfo* OldLevel;
    FStringNoInit RUserDirectory;
    FStringNoInit PlayList[256];
    INT PlaylistEntires;
    DECLARE_FUNCTION(execPlayUnLoopSong);
    DECLARE_FUNCTION(execReadUserDirectory);
    DECLARE_FUNCTION(execShutdown);
    DECLARE_FUNCTION(execPlayNewSong);
    DECLARE_FUNCTION(execChangeVolume);
    DECLARE_FUNCTION(execStopSong);
    DECLARE_FUNCTION(execPlaySong);
    DECLARE_FUNCTION(execMusicSystemInit);
    void eventReadPlaylist()
    {
        ProcessEvent(FindFunctionChecked(RVMP3PLAYER_ReadPlaylist),NULL);
    }
    FString eventAddSlashes(const FString& sourcestring)
    {
        ARMp3Player_eventAddSlashes_Parms Parms;
        Parms.sourcestring=sourcestring;
        ProcessEvent(FindFunctionChecked(RVMP3PLAYER_AddSlashes),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(ARMp3Player,AActor,0|CLASS_Config,RvMp3Player)
    NO_DEFAULT_CONSTRUCTOR(ARMp3Player)
};

#endif

AUTOGENERATE_FUNCTION(ARMp3Player,-1,execPlayUnLoopSong);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execReadUserDirectory);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execShutdown);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execPlayNewSong);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execChangeVolume);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execStopSong);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execPlaySong);
AUTOGENERATE_FUNCTION(ARMp3Player,-1,execMusicSystemInit);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
