/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef RWINAMPCONTROLLER_API
#define RWINAMPCONTROLLER_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern RWINAMPCONTROLLER_API FName RWINAMPCONTROLLER_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class RWINAMPCONTROLLER_API AWinampController : public AActor
{
public:
    DECLARE_FUNCTION(execWNP_FastRewind);
    DECLARE_FUNCTION(execWNP_FastForward);
    DECLARE_FUNCTION(execWNP_LowerVolume);
    DECLARE_FUNCTION(execWNP_RaiseVolume);
    DECLARE_FUNCTION(execWNP_ToggleShuffle);
    DECLARE_FUNCTION(execWNP_ToggleRepeat);
    DECLARE_FUNCTION(execWNP_PreviousTrack);
    DECLARE_FUNCTION(execWNP_NextTrack);
    DECLARE_FUNCTION(execWNP_PlayOrPause);
    DECLARE_FUNCTION(execWNP_Stop);
    DECLARE_FUNCTION(execWNP_Play);
    DECLARE_FUNCTION(execWNP_IsActive);
    DECLARE_CLASS(AWinampController,AActor,0,RWinampController)
    NO_DEFAULT_CONSTRUCTOR(AWinampController)
};

#endif

AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_FastRewind);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_FastForward);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_LowerVolume);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_RaiseVolume);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_ToggleShuffle);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_ToggleRepeat);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_PreviousTrack);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_NextTrack);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_PlayOrPause);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_Stop);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_Play);
AUTOGENERATE_FUNCTION(AWinampController,-1,execWNP_IsActive);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
