<?xml version="1.0"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
		<id>https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom</id>
		<title>Wikipedia &quot;On this day...&quot; feed</title>
		<link rel="self" type="application/atom+xml" href="https://en.wikipedia.org/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom"/>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Main_Page"/>
		<updated>2016-12-16T19:01:46Z</updated>
		<subtitle>Historical events on this day</subtitle>
		<generator>MediaWiki 1.29.0-wmf.6</generator>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161207000000/en</id>
		<title>On this day: December 7</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161207000000/en"/>
				<updated>2016-12-07T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_7&quot; title=&quot;December 7&quot;&gt;December 7&lt;/a&gt;&lt;/b&gt;:  &lt;b&gt;&lt;a href=&quot;/wiki/Armed_Forces_Flag_Day&quot; title=&quot;Armed Forces Flag Day&quot;&gt;Armed Forces Flag Day&lt;/a&gt;&lt;/b&gt; in India; &lt;b&gt;&lt;a href=&quot;/wiki/National_Pearl_Harbor_Remembrance_Day&quot; title=&quot;National Pearl Harbor Remembrance Day&quot;&gt;Pearl Harbor Day&lt;/a&gt;&lt;/b&gt; in the United States
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 100px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Jesse_james_portrait.jpg&quot; class=&quot;image&quot; title=&quot;Jesse James&quot;&gt;&lt;img alt=&quot;Jesse James&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/2/22/Jesse_james_portrait.jpg/100px-Jesse_james_portrait.jpg&quot; width=&quot;100&quot; height=&quot;138&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/2/22/Jesse_james_portrait.jpg/150px-Jesse_james_portrait.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/22/Jesse_james_portrait.jpg/200px-Jesse_james_portrait.jpg 2x&quot; data-file-width=&quot;1115&quot; data-file-height=&quot;1536&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Jesse James&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1815&quot; title=&quot;1815&quot;&gt;1815&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Michel_Ney&quot; title=&quot;Michel Ney&quot;&gt;Michel Ney&lt;/a&gt;&lt;/b&gt;, &lt;a href=&quot;/wiki/Marshal_of_France&quot; class=&quot;mw-redirect&quot; title=&quot;Marshal of France&quot;&gt;Marshal of France&lt;/a&gt;, was executed by a firing squad near Paris' &lt;a href=&quot;/wiki/Jardin_du_Luxembourg&quot; title=&quot;Jardin du Luxembourg&quot;&gt;Jardin du Luxembourg&lt;/a&gt; for supporting &lt;a href=&quot;/wiki/Napoleon&quot; title=&quot;Napoleon&quot;&gt;Napoleon&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1869&quot; title=&quot;1869&quot;&gt;1869&lt;/a&gt; – American outlaw &lt;b&gt;&lt;a href=&quot;/wiki/Jesse_James&quot; title=&quot;Jesse James&quot;&gt;Jesse James&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; committed his first confirmed bank robbery in &lt;a href=&quot;/wiki/Gallatin,_Missouri&quot; title=&quot;Gallatin, Missouri&quot;&gt;Gallatin, Missouri&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1936&quot; title=&quot;1936&quot;&gt;1936&lt;/a&gt; – Australian &lt;a href=&quot;/wiki/Cricket&quot; title=&quot;Cricket&quot;&gt;cricketer&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Jack_Fingleton&quot; title=&quot;Jack Fingleton&quot;&gt;Jack Fingleton&lt;/a&gt;&lt;/b&gt; became the first player to score &lt;a href=&quot;/wiki/Century_(cricket)&quot; title=&quot;Century (cricket)&quot;&gt;centuries&lt;/a&gt; in four consecutive &lt;a href=&quot;/wiki/Test_cricket&quot; title=&quot;Test cricket&quot;&gt;Test&lt;/a&gt; innings.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1946&quot; title=&quot;1946&quot;&gt;1946&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Winecoff_Hotel_fire&quot; title=&quot;Winecoff Hotel fire&quot;&gt;deadliest hotel fire in U.S. history&lt;/a&gt;&lt;/b&gt; happened at the &lt;a href=&quot;/wiki/Winecoff_Hotel&quot; class=&quot;mw-redirect&quot; title=&quot;Winecoff Hotel&quot;&gt;Winecoff Hotel&lt;/a&gt; in &lt;a href=&quot;/wiki/Atlanta&quot; title=&quot;Atlanta&quot;&gt;Atlanta, Georgia&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1988&quot; title=&quot;1988&quot;&gt;1988&lt;/a&gt; – A &lt;span class=&quot;nowrap&quot;&gt;6.9 &lt;a href=&quot;/wiki/Moment_magnitude_scale&quot; title=&quot;Moment magnitude scale&quot;&gt;M&lt;sub&gt;w&lt;/sub&gt;&lt;/a&gt;&lt;/span&gt; earthquake &lt;b&gt;&lt;a href=&quot;/wiki/1988_Armenian_earthquake&quot; title=&quot;1988 Armenian earthquake&quot;&gt;struck&lt;/a&gt;&lt;/b&gt; the &lt;a href=&quot;/wiki/Spitak&quot; title=&quot;Spitak&quot;&gt;Spitak&lt;/a&gt; region of Armenia, killing at least 25,000 people.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_6&quot; title=&quot;December 6&quot;&gt;December 6&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_7&quot; title=&quot;December 7&quot;&gt;December 7&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_8&quot; title=&quot;December 8&quot;&gt;December 8&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 7, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161208000000/en</id>
		<title>On this day: December 8</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161208000000/en"/>
				<updated>2016-12-08T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_8&quot; title=&quot;December 8&quot;&gt;December 8&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Bodhi_Day&quot; title=&quot;Bodhi Day&quot;&gt;Rōhatsu&lt;/a&gt;&lt;/b&gt; in Japan
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 120px;&quot;&gt;
&lt;a href=&quot;/wiki/File:IKAROS_IAC_2010.jpg&quot; class=&quot;image&quot; title=&quot;Model of the IKAROS spacecraft&quot;&gt;&lt;img alt=&quot;Model of the IKAROS spacecraft&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/1/17/IKAROS_IAC_2010.jpg/120px-IKAROS_IAC_2010.jpg&quot; width=&quot;120&quot; height=&quot;101&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/1/17/IKAROS_IAC_2010.jpg/180px-IKAROS_IAC_2010.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/17/IKAROS_IAC_2010.jpg/240px-IKAROS_IAC_2010.jpg 2x&quot; data-file-width=&quot;2190&quot; data-file-height=&quot;1851&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Model of the IKAROS spacecraft&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1660&quot; title=&quot;1660&quot;&gt;1660&lt;/a&gt; – A woman, thought to be &lt;b&gt;&lt;a href=&quot;/wiki/Margaret_Hughes&quot; title=&quot;Margaret Hughes&quot;&gt;Margaret Hughes&lt;/a&gt;&lt;/b&gt;, first appeared professionally on stage.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1880&quot; title=&quot;1880&quot;&gt;1880&lt;/a&gt; – At an assembly of 10,000 &lt;a href=&quot;/wiki/Boer&quot; title=&quot;Boer&quot;&gt;Boers&lt;/a&gt;, &lt;b&gt;&lt;a href=&quot;/wiki/Paul_Kruger&quot; title=&quot;Paul Kruger&quot;&gt;Paul Kruger&lt;/a&gt;&lt;/b&gt; announced the fulfilment of the decision to restore the &lt;a href=&quot;/wiki/South_African_Republic&quot; title=&quot;South African Republic&quot;&gt;South African Republic&lt;/a&gt; government and &lt;a href=&quot;/wiki/Volksraad&quot; title=&quot;Volksraad&quot;&gt;volksraad&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – &lt;a href=&quot;/wiki/The_Holocaust&quot; title=&quot;The Holocaust&quot;&gt;The Holocaust&lt;/a&gt;: The &lt;b&gt;&lt;a href=&quot;/wiki/Che%C5%82mno_extermination_camp&quot; title=&quot;Chełmno extermination camp&quot;&gt;Chełmno extermination camp&lt;/a&gt;&lt;/b&gt; in &lt;a href=&quot;/wiki/Occupation_of_Poland_(1939%E2%80%931945)&quot; class=&quot;mw-redirect&quot; title=&quot;Occupation of Poland (1939–1945)&quot;&gt;occupied Poland&lt;/a&gt;, the first such Nazi camp to kill the Jews of the &lt;a href=&quot;/wiki/Ghetto_Litzmannstadt&quot; class=&quot;mw-redirect&quot; title=&quot;Ghetto Litzmannstadt&quot;&gt;Ghetto Litzmannstadt&lt;/a&gt; and the &lt;a href=&quot;/wiki/Reichsgau_Wartheland&quot; title=&quot;Reichsgau Wartheland&quot;&gt;Warthegau&lt;/a&gt; by &lt;a href=&quot;/wiki/Gas_chamber&quot; title=&quot;Gas chamber&quot;&gt;poison gas&lt;/a&gt;, began operating.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1991&quot; title=&quot;1991&quot;&gt;1991&lt;/a&gt; – Leaders of Belarus, Russia and Ukraine signed the &lt;a href=&quot;/wiki/Belavezha_Accords&quot; title=&quot;Belavezha Accords&quot;&gt;Belavezha Accords&lt;/a&gt;, agreeing to &lt;a href=&quot;/wiki/Dissolution_of_the_Soviet_Union&quot; title=&quot;Dissolution of the Soviet Union&quot;&gt;dissolve the Soviet Union&lt;/a&gt; and establish the &lt;b&gt;&lt;a href=&quot;/wiki/Commonwealth_of_Independent_States&quot; title=&quot;Commonwealth of Independent States&quot;&gt;Commonwealth of Independent States&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/2010&quot; title=&quot;2010&quot;&gt;2010&lt;/a&gt; – The Japanese experimental spacecraft &lt;b&gt;&lt;a href=&quot;/wiki/IKAROS&quot; title=&quot;IKAROS&quot;&gt;IKAROS&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(model pictured)&lt;/i&gt; passed by Venus at about &lt;span class=&quot;nowrap&quot;&gt;80,800 km&lt;/span&gt; distance, completing its planned mission to demonstrate &lt;a href=&quot;/wiki/Solar_sail&quot; title=&quot;Solar sail&quot;&gt;solar sail&lt;/a&gt; technology.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_7&quot; title=&quot;December 7&quot;&gt;December 7&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_8&quot; title=&quot;December 8&quot;&gt;December 8&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_9&quot; title=&quot;December 9&quot;&gt;December 9&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 8, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161209000000/en</id>
		<title>On this day: December 9</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161209000000/en"/>
				<updated>2016-12-09T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_9&quot; title=&quot;December 9&quot;&gt;December 9&lt;/a&gt;&lt;/b&gt;: 100th birthday of actor &lt;b&gt;&lt;a href=&quot;/wiki/Kirk_Douglas&quot; title=&quot;Kirk Douglas&quot;&gt;Kirk Douglas&lt;/a&gt;&lt;/b&gt; 
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 100px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Ottoman_surrender_of_Jerusalem_restored.jpg&quot; class=&quot;image&quot; title=&quot;The surrender of Jerusalem&quot;&gt;&lt;img alt=&quot;The surrender of Jerusalem&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Ottoman_surrender_of_Jerusalem_restored.jpg/100px-Ottoman_surrender_of_Jerusalem_restored.jpg&quot; width=&quot;100&quot; height=&quot;131&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Ottoman_surrender_of_Jerusalem_restored.jpg/150px-Ottoman_surrender_of_Jerusalem_restored.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/Ottoman_surrender_of_Jerusalem_restored.jpg/200px-Ottoman_surrender_of_Jerusalem_restored.jpg 2x&quot; data-file-width=&quot;2995&quot; data-file-height=&quot;3913&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;The surrender of Jerusalem&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1872&quot; title=&quot;1872&quot;&gt;1872&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/P._B._S._Pinchback&quot; title=&quot;P. B. S. Pinchback&quot;&gt;P. B. S. Pinchback&lt;/a&gt;&lt;/b&gt; took office as &lt;a href=&quot;/wiki/List_of_Governors_of_Louisiana&quot; title=&quot;List of Governors of Louisiana&quot;&gt;Governor of Louisiana&lt;/a&gt;, the first &lt;a href=&quot;/wiki/African_American&quot; class=&quot;mw-redirect&quot; title=&quot;African American&quot;&gt;African American&lt;/a&gt; governor of a U.S. state.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1905&quot; title=&quot;1905&quot;&gt;1905&lt;/a&gt; – Legislation establishing &lt;a href=&quot;/wiki/State_secularism&quot; class=&quot;mw-redirect&quot; title=&quot;State secularism&quot;&gt;state secularism&lt;/a&gt; in France &lt;b&gt;&lt;a href=&quot;/wiki/1905_French_law_on_the_Separation_of_the_Churches_and_the_State&quot; title=&quot;1905 French law on the Separation of the Churches and the State&quot;&gt;was passed&lt;/a&gt;&lt;/b&gt; by the &lt;a href=&quot;/wiki/Chamber_of_Deputies_of_France&quot; class=&quot;mw-redirect&quot; title=&quot;Chamber of Deputies of France&quot;&gt;Chamber of Deputies of France&lt;/a&gt;, triggering &lt;a href=&quot;/wiki/Civil_disobedience&quot; title=&quot;Civil disobedience&quot;&gt;civil disobedience&lt;/a&gt; by &lt;a href=&quot;/wiki/Roman_Catholicism_in_France&quot; class=&quot;mw-redirect&quot; title=&quot;Roman Catholicism in France&quot;&gt;French Catholics&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1917&quot; title=&quot;1917&quot;&gt;1917&lt;/a&gt; – &lt;a href=&quot;/wiki/World_War_I&quot; title=&quot;World War I&quot;&gt;First World War&lt;/a&gt;: &lt;a href=&quot;/wiki/Hussein_al-Husayni&quot; title=&quot;Hussein al-Husayni&quot;&gt;Hussein al-Husayni&lt;/a&gt;, the Ottoman &lt;a href=&quot;/wiki/Mayor_of_Jerusalem&quot; title=&quot;Mayor of Jerusalem&quot;&gt;mayor of Jerusalem&lt;/a&gt;, &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Jerusalem&quot; title=&quot;Battle of Jerusalem&quot;&gt;surrendered&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt; the city to the British.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1948&quot; title=&quot;1948&quot;&gt;1948&lt;/a&gt; – The &lt;a href=&quot;/wiki/United_Nations_General_Assembly&quot; title=&quot;United Nations General Assembly&quot;&gt;United Nations General Assembly&lt;/a&gt; adopted the &lt;b&gt;&lt;a href=&quot;/wiki/Genocide_Convention&quot; title=&quot;Genocide Convention&quot;&gt;Genocide Convention&lt;/a&gt;&lt;/b&gt;, which defines &lt;a href=&quot;/wiki/Genocide&quot; title=&quot;Genocide&quot;&gt;genocide&lt;/a&gt; in legal terms and advises its signatories to prevent and punish such actions.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1968&quot; title=&quot;1968&quot;&gt;1968&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Douglas_Engelbart&quot; title=&quot;Douglas Engelbart&quot;&gt;Douglas Engelbart&lt;/a&gt;&lt;/b&gt; gave what became known as &quot;&lt;b&gt;&lt;a href=&quot;/wiki/The_Mother_of_All_Demos&quot; title=&quot;The Mother of All Demos&quot;&gt;The Mother of All Demos&lt;/a&gt;&lt;/b&gt;&quot;, publicly debuting the &lt;a href=&quot;/wiki/Mouse_(computer)&quot; class=&quot;mw-redirect&quot; title=&quot;Mouse (computer)&quot;&gt;computer mouse&lt;/a&gt;, &lt;a href=&quot;/wiki/Hypertext&quot; title=&quot;Hypertext&quot;&gt;hypertext&lt;/a&gt;, and the bit-mapped &lt;a href=&quot;/wiki/Graphical_user_interface&quot; title=&quot;Graphical user interface&quot;&gt;graphical user interface&lt;/a&gt; using the &lt;a href=&quot;/wiki/NLS_(computer_system)&quot; title=&quot;NLS (computer system)&quot;&gt;oN-Line System (NLS)&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_8&quot; title=&quot;December 8&quot;&gt;December 8&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_9&quot; title=&quot;December 9&quot;&gt;December 9&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_10&quot; title=&quot;December 10&quot;&gt;December 10&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 9, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161210000000/en</id>
		<title>On this day: December 10</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161210000000/en"/>
				<updated>2016-12-10T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_10&quot; title=&quot;December 10&quot;&gt;December 10&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Human_Rights_Day&quot; title=&quot;Human Rights Day&quot;&gt;Human Rights Day&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 100px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Wallis_Simpson_-1936.JPG&quot; class=&quot;image&quot; title=&quot;Wallis Simpson&quot;&gt;&lt;img alt=&quot;Wallis Simpson&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Wallis_Simpson_-1936.JPG/100px-Wallis_Simpson_-1936.JPG&quot; width=&quot;100&quot; height=&quot;127&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Wallis_Simpson_-1936.JPG/150px-Wallis_Simpson_-1936.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/33/Wallis_Simpson_-1936.JPG/200px-Wallis_Simpson_-1936.JPG 2x&quot; data-file-width=&quot;471&quot; data-file-height=&quot;597&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Wallis Simpson&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1799&quot; title=&quot;1799&quot;&gt;1799&lt;/a&gt; – France became the first country to &lt;b&gt;&lt;a href=&quot;/wiki/History_of_the_metric_system&quot; title=&quot;History of the metric system&quot;&gt;adopt&lt;/a&gt;&lt;/b&gt; the &lt;a href=&quot;/wiki/Metric_system&quot; title=&quot;Metric system&quot;&gt;metric system&lt;/a&gt; as its system for weights and measures.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1898&quot; title=&quot;1898&quot;&gt;1898&lt;/a&gt; – The &lt;a href=&quot;/wiki/Spanish%E2%80%93American_War&quot; title=&quot;Spanish–American War&quot;&gt;Spanish–American War&lt;/a&gt; ended with the signing of the &lt;b&gt;&lt;a href=&quot;/wiki/Treaty_of_Paris_(1898)&quot; title=&quot;Treaty of Paris (1898)&quot;&gt;Treaty of Paris&lt;/a&gt;&lt;/b&gt;, with Spain recognizing the independence of Cuba; and ceding Guam, the Philippines, and Puerto Rico to the United States.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1936&quot; title=&quot;1936&quot;&gt;1936&lt;/a&gt; – &lt;a href=&quot;/wiki/Edward_VIII&quot; title=&quot;Edward VIII&quot;&gt;Edward VIII&lt;/a&gt;, desiring to marry American &lt;a href=&quot;/wiki/Socialite&quot; title=&quot;Socialite&quot;&gt;socialite&lt;/a&gt; &lt;a href=&quot;/wiki/Wallis,_Duchess_of_Windsor&quot; class=&quot;mw-redirect&quot; title=&quot;Wallis, Duchess of Windsor&quot;&gt;Wallis Simpson&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt; against widespread opposition, &lt;b&gt;&lt;a href=&quot;/wiki/Edward_VIII_abdication_crisis&quot; title=&quot;Edward VIII abdication crisis&quot;&gt;abdicated the throne&lt;/a&gt;&lt;/b&gt;, the only British monarch to have voluntarily done so since the &lt;a href=&quot;/wiki/Anglo-Saxons&quot; title=&quot;Anglo-Saxons&quot;&gt;Anglo-Saxon&lt;/a&gt; period.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – &lt;a href=&quot;/wiki/World_War_II&quot; title=&quot;World War II&quot;&gt;Second World War&lt;/a&gt;: &lt;a href=&quot;/wiki/Imperial_Japanese_Navy&quot; title=&quot;Imperial Japanese Navy&quot;&gt;Imperial Japanese Navy&lt;/a&gt; &lt;a href=&quot;/wiki/Torpedo_bomber&quot; title=&quot;Torpedo bomber&quot;&gt;torpedo bombers&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Sinking_of_Prince_of_Wales_and_Repulse&quot; title=&quot;Sinking of Prince of Wales and Repulse&quot;&gt;sank&lt;/a&gt;&lt;/b&gt; the &lt;a href=&quot;/wiki/Royal_Navy&quot; title=&quot;Royal Navy&quot;&gt;Royal Navy&lt;/a&gt; capital ships &lt;a href=&quot;/wiki/HMS_Prince_of_Wales_(53)&quot; title=&quot;HMS Prince of Wales (53)&quot;&gt;HMS&amp;#160;&lt;i&gt;Prince of Wales&lt;/i&gt;&lt;/a&gt; and &lt;a href=&quot;/wiki/HMS_Repulse_(1916)&quot; title=&quot;HMS Repulse (1916)&quot;&gt;HMS&amp;#160;&lt;i&gt;Repulse&lt;/i&gt;&lt;/a&gt; east of &lt;a href=&quot;/wiki/Peninsular_Malaysia&quot; title=&quot;Peninsular Malaysia&quot;&gt;Malaya&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1989&quot; title=&quot;1989&quot;&gt;1989&lt;/a&gt; – At the first open pro-democracy demonstration in Mongolia, journalist &lt;b&gt;&lt;a href=&quot;/wiki/Tsakhiagiin_Elbegdorj&quot; title=&quot;Tsakhiagiin Elbegdorj&quot;&gt;Tsakhiagiin Elbegdorj&lt;/a&gt;&lt;/b&gt; announced the formation of the &lt;a href=&quot;/wiki/Mongolian_Democratic_Union&quot; class=&quot;mw-redirect&quot; title=&quot;Mongolian Democratic Union&quot;&gt;Mongolian Democratic Union&lt;/a&gt;, which would be instrumental in ending Communist rule four months later.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_9&quot; title=&quot;December 9&quot;&gt;December 9&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_10&quot; title=&quot;December 10&quot;&gt;December 10&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_11&quot; title=&quot;December 11&quot;&gt;December 11&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 10, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161211000000/en</id>
		<title>On this day: December 11</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161211000000/en"/>
				<updated>2016-12-11T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_11&quot; title=&quot;December 11&quot;&gt;December 11&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Mawlid&quot; title=&quot;Mawlid&quot;&gt;Mawlid&lt;/a&gt;&lt;/b&gt; begins at sunset (&lt;a href=&quot;/wiki/Sunni_Islam&quot; title=&quot;Sunni Islam&quot;&gt;Sunni Islam&lt;/a&gt;, 2016); &lt;a href=&quot;/wiki/Republic_Day&quot; title=&quot;Republic Day&quot;&gt;Republic Day&lt;/a&gt; in &lt;b&gt;&lt;a href=&quot;/wiki/Burkina_Faso&quot; title=&quot;Burkina Faso&quot;&gt;Burkina Faso&lt;/a&gt;&lt;/b&gt; (&lt;a href=&quot;/wiki/1958&quot; title=&quot;1958&quot;&gt;1958&lt;/a&gt;)
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 100px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Shulyavska_respublika.jpg&quot; class=&quot;image&quot; title=&quot;Monument to the workers of the Shuliavka Republic&quot;&gt;&lt;img alt=&quot;Monument to the workers of the Shuliavka Republic&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Shulyavska_respublika.jpg/100px-Shulyavska_respublika.jpg&quot; width=&quot;100&quot; height=&quot;149&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Shulyavska_respublika.jpg/150px-Shulyavska_respublika.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Shulyavska_respublika.jpg/200px-Shulyavska_respublika.jpg 2x&quot; data-file-width=&quot;279&quot; data-file-height=&quot;415&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Monument to the workers of the Shuliavka Republic&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/220&quot; title=&quot;220&quot;&gt;220&lt;/a&gt; – &lt;a href=&quot;/wiki/Emperor_Xian_of_Han&quot; title=&quot;Emperor Xian of Han&quot;&gt;Emperor Xian&lt;/a&gt; abdicated the throne and the &lt;a href=&quot;/wiki/Han_dynasty&quot; title=&quot;Han dynasty&quot;&gt;Han dynasty&lt;/a&gt; broke apart, beginning the &lt;b&gt;&lt;a href=&quot;/wiki/Three_Kingdoms&quot; title=&quot;Three Kingdoms&quot;&gt;Three Kingdoms&lt;/a&gt;&lt;/b&gt; period in China.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1899&quot; title=&quot;1899&quot;&gt;1899&lt;/a&gt; – &lt;a href=&quot;/wiki/Second_Boer_War&quot; title=&quot;Second Boer War&quot;&gt;Second Boer War&lt;/a&gt;: In the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Magersfontein&quot; title=&quot;Battle of Magersfontein&quot;&gt;Battle of Magersfontein&lt;/a&gt;&lt;/b&gt;, &lt;a href=&quot;/wiki/Boer&quot; title=&quot;Boer&quot;&gt;Boers&lt;/a&gt; defeated the forces of the &lt;a href=&quot;/wiki/British_Empire&quot; title=&quot;British Empire&quot;&gt;British Empire&lt;/a&gt; trying to relieve the &lt;a href=&quot;/wiki/Siege_of_Kimberley&quot; title=&quot;Siege of Kimberley&quot;&gt;Siege of Kimberley&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1905&quot; title=&quot;1905&quot;&gt;1905&lt;/a&gt; – In support of the December Uprising in &lt;a href=&quot;/wiki/Moscow&quot; title=&quot;Moscow&quot;&gt;Moscow&lt;/a&gt;, the Council of Workers' Deputies of &lt;a href=&quot;/wiki/Kiev&quot; title=&quot;Kiev&quot;&gt;Kiev&lt;/a&gt; staged a mass uprising, establishing the &lt;b&gt;&lt;a href=&quot;/wiki/Shuliavka_Republic&quot; title=&quot;Shuliavka Republic&quot;&gt;Shuliavka Republic&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(monument pictured)&lt;/i&gt; in the city.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1980&quot; title=&quot;1980&quot;&gt;1980&lt;/a&gt; – The &lt;a href=&quot;/wiki/United_States_Congress&quot; title=&quot;United States Congress&quot;&gt;United States Congress&lt;/a&gt; enacted the &lt;b&gt;&lt;a href=&quot;/wiki/Superfund&quot; title=&quot;Superfund&quot;&gt;Comprehensive Environmental Response, Compensation, and Liability Act&lt;/a&gt;&lt;/b&gt; to protect people, families, communities and others from heavily contaminated &lt;a href=&quot;/wiki/Toxic_waste&quot; title=&quot;Toxic waste&quot;&gt;toxic waste&lt;/a&gt; sites that have been abandoned.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/2006&quot; title=&quot;2006&quot;&gt;2006&lt;/a&gt; – The first action in the &lt;b&gt;&lt;a href=&quot;/wiki/Mexican_Drug_War&quot; title=&quot;Mexican Drug War&quot;&gt;Mexican Drug War&lt;/a&gt;&lt;/b&gt; took place as President &lt;a href=&quot;/wiki/Felipe_Calder%C3%B3n&quot; title=&quot;Felipe Calderón&quot;&gt;Felipe Calderón&lt;/a&gt; &lt;a href=&quot;/wiki/Operation_Michoacan&quot; class=&quot;mw-redirect&quot; title=&quot;Operation Michoacan&quot;&gt;ordered&lt;/a&gt; &lt;a href=&quot;/wiki/Military_of_Mexico&quot; class=&quot;mw-redirect&quot; title=&quot;Military of Mexico&quot;&gt;Mexican military&lt;/a&gt; and &lt;a href=&quot;/wiki/Federal_Police_(Mexico)&quot; title=&quot;Federal Police (Mexico)&quot;&gt;Federal Police&lt;/a&gt; units into the state of &lt;a href=&quot;/wiki/Michoac%C3%A1n&quot; title=&quot;Michoacán&quot;&gt;Michoacán&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_10&quot; title=&quot;December 10&quot;&gt;December 10&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_11&quot; title=&quot;December 11&quot;&gt;December 11&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 11, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161212000000/en</id>
		<title>On this day: December 12</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161212000000/en"/>
				<updated>2016-12-12T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Yule_Lads&quot; title=&quot;Yule Lads&quot;&gt;Yule Lads&lt;/a&gt;&lt;/b&gt; begin arrival in Iceland
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 122px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg&quot; class=&quot;image&quot; title=&quot;Scene of the Clapham Junction rail crash&quot;&gt;&lt;img alt=&quot;Scene of the Clapham Junction rail crash&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg/120px-Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg&quot; width=&quot;120&quot; height=&quot;90&quot; class=&quot;thumbborder&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg/180px-Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg/240px-Clapham_Junction_1988_incident_2_geograph-3149688-by-Ben-Brooksbank.jpg 2x&quot; data-file-width=&quot;1920&quot; data-file-height=&quot;1440&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Scene of the Clapham Junction rail crash&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/627&quot; title=&quot;627&quot;&gt;627&lt;/a&gt; – A &lt;a href=&quot;/wiki/Byzantine_Empire&quot; title=&quot;Byzantine Empire&quot;&gt;Byzantine&lt;/a&gt; army under Emperor &lt;a href=&quot;/wiki/Heraclius&quot; title=&quot;Heraclius&quot;&gt;Heraclius&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Nineveh_(627)&quot; title=&quot;Battle of Nineveh (627)&quot;&gt;defeated&lt;/a&gt;&lt;/b&gt; Emperor &lt;span class=&quot;nowrap&quot;&gt;&lt;a href=&quot;/wiki/Khosrau_II&quot; class=&quot;mw-redirect&quot; title=&quot;Khosrau II&quot;&gt;Khosrau II&lt;/a&gt;'s&lt;/span&gt; &lt;a href=&quot;/wiki/Persian_Empire&quot; title=&quot;Persian Empire&quot;&gt;Persian&lt;/a&gt; forces, commanded by &lt;a href=&quot;/wiki/Rhahzadh&quot; title=&quot;Rhahzadh&quot;&gt;General Rhahzadh&lt;/a&gt;, near present-day &lt;a href=&quot;/wiki/Mosul&quot; title=&quot;Mosul&quot;&gt;Mosul&lt;/a&gt;, Iraq.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1531&quot; title=&quot;1531&quot;&gt;1531&lt;/a&gt; – According to traditional Catholic accounts, the image of the &lt;a href=&quot;/wiki/Veneration_of_Mary_in_Roman_Catholicism&quot; class=&quot;mw-redirect&quot; title=&quot;Veneration of Mary in Roman Catholicism&quot;&gt;Blessed Virgin Mary&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Our_Lady_of_Guadalupe&quot; title=&quot;Our Lady of Guadalupe&quot;&gt;miraculously appeared&lt;/a&gt;&lt;/b&gt; imprinted on &lt;a href=&quot;/wiki/Juan_Diego&quot; title=&quot;Juan Diego&quot;&gt;Juan Diego&lt;/a&gt;'s &lt;a href=&quot;/wiki/Tilm%C3%A0tli&quot; title=&quot;Tilmàtli&quot;&gt;tilma&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1866&quot; title=&quot;1866&quot;&gt;1866&lt;/a&gt; – England's worst mining disaster occurred when &lt;b&gt;&lt;a href=&quot;/wiki/Oaks_explosion&quot; title=&quot;Oaks explosion&quot;&gt;a series of explosions&lt;/a&gt;&lt;/b&gt; caused by &lt;a href=&quot;/wiki/Firedamp&quot; title=&quot;Firedamp&quot;&gt;flammable gases&lt;/a&gt; ripped through the Oaks Colliery.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1941&quot; title=&quot;1941&quot;&gt;1941&lt;/a&gt; – At a &lt;a href=&quot;/wiki/Nazi_Party&quot; title=&quot;Nazi Party&quot;&gt;Nazi Party&lt;/a&gt; meeting in the &lt;a href=&quot;/wiki/Reich_Chancellery&quot; title=&quot;Reich Chancellery&quot;&gt;Reich Chancellery&lt;/a&gt;, &lt;a href=&quot;/wiki/Adolf_Hitler&quot; title=&quot;Adolf Hitler&quot;&gt;Adolf Hitler&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Reich_Chancellery_meeting_of_12_December_1941&quot; title=&quot;Reich Chancellery meeting of 12 December 1941&quot;&gt;declared&lt;/a&gt;&lt;/b&gt; the imminent destruction of the &lt;a href=&quot;/wiki/Jews&quot; title=&quot;Jews&quot;&gt;Jewish&lt;/a&gt; people.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1956&quot; title=&quot;1956&quot;&gt;1956&lt;/a&gt; – The &lt;a href=&quot;/wiki/Irish_Republican_Army_(1922%E2%80%9369)&quot; title=&quot;Irish Republican Army (1922–69)&quot;&gt;Irish Republican Army&lt;/a&gt; began its &lt;b&gt;&lt;a href=&quot;/wiki/Border_Campaign_(Irish_Republican_Army)&quot; title=&quot;Border Campaign (Irish Republican Army)&quot;&gt;Border Campaign&lt;/a&gt;&lt;/b&gt;, a &lt;a href=&quot;/wiki/Guerrilla_warfare&quot; title=&quot;Guerrilla warfare&quot;&gt;guerrilla&lt;/a&gt; campaign to overthrow British rule in &lt;a href=&quot;/wiki/Northern_Ireland&quot; title=&quot;Northern Ireland&quot;&gt;Northern Ireland&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1988&quot; title=&quot;1988&quot;&gt;1988&lt;/a&gt; – Three trains &lt;b&gt;&lt;a href=&quot;/wiki/Clapham_Junction_rail_crash&quot; title=&quot;Clapham Junction rail crash&quot;&gt;collided&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(scene pictured)&lt;/i&gt; near &lt;a href=&quot;/wiki/Clapham_Junction_railway_station&quot; title=&quot;Clapham Junction railway station&quot;&gt;Clapham Junction railway station&lt;/a&gt; in London, killing 35 people and injuring 484 others.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_11&quot; title=&quot;December 11&quot;&gt;December 11&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 12, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161213000000/en</id>
		<title>On this day: December 13</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161213000000/en"/>
				<updated>2016-12-13T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Saint_Lucy%27s_Day&quot; title=&quot;Saint Lucy's Day&quot;&gt;Saint Lucy's Day&lt;/a&gt;&lt;/b&gt; in Italy and Scandinavia
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 100px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Selassie_restored.jpg&quot; class=&quot;image&quot; title=&quot;Haile Selassie&quot;&gt;&lt;img alt=&quot;Haile Selassie&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Selassie_restored.jpg/100px-Selassie_restored.jpg&quot; width=&quot;100&quot; height=&quot;131&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Selassie_restored.jpg/150px-Selassie_restored.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/32/Selassie_restored.jpg/200px-Selassie_restored.jpg 2x&quot; data-file-width=&quot;2494&quot; data-file-height=&quot;3257&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Haile Selassie&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1862&quot; title=&quot;1862&quot;&gt;1862&lt;/a&gt; – &lt;a href=&quot;/wiki/American_Civil_War&quot; title=&quot;American Civil War&quot;&gt;American Civil War&lt;/a&gt;: &lt;a href=&quot;/wiki/Union_Army&quot; title=&quot;Union Army&quot;&gt;Union forces&lt;/a&gt; under &lt;a href=&quot;/wiki/Major_General&quot; class=&quot;mw-redirect&quot; title=&quot;Major General&quot;&gt;Major General&lt;/a&gt; &lt;a href=&quot;/wiki/Ambrose_Burnside&quot; title=&quot;Ambrose Burnside&quot;&gt;Ambrose Burnside&lt;/a&gt; suffered severe casualties against entrenched &lt;a href=&quot;/wiki/Confederate_States_of_America&quot; title=&quot;Confederate States of America&quot;&gt;Confederate&lt;/a&gt; defenders at the &lt;b&gt;&lt;a href=&quot;/wiki/Battle_of_Fredericksburg&quot; title=&quot;Battle of Fredericksburg&quot;&gt;Battle of Fredericksburg&lt;/a&gt;&lt;/b&gt; in &lt;a href=&quot;/wiki/Fredericksburg,_Virginia&quot; title=&quot;Fredericksburg, Virginia&quot;&gt;Fredericksburg, Virginia&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1960&quot; title=&quot;1960&quot;&gt;1960&lt;/a&gt; – With &lt;a href=&quot;/wiki/Haile_Selassie&quot; title=&quot;Haile Selassie&quot;&gt;Haile Selassie&lt;/a&gt; &lt;i&gt;(pictured)&lt;/i&gt;, the &lt;a href=&quot;/wiki/Emperor_of_Ethiopia&quot; title=&quot;Emperor of Ethiopia&quot;&gt;Emperor of Ethiopia&lt;/a&gt;, out of the country, four conspirators staged a &lt;b&gt;&lt;a href=&quot;/wiki/1960_Ethiopian_coup_attempt&quot; title=&quot;1960 Ethiopian coup attempt&quot;&gt;coup attempt&lt;/a&gt;&lt;/b&gt; and installed &lt;a href=&quot;/wiki/Amha_Selassie&quot; title=&quot;Amha Selassie&quot;&gt;Crown Prince Asfaw Wossen&lt;/a&gt; as the new Emperor. &lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1989&quot; title=&quot;1989&quot;&gt;1989&lt;/a&gt; – &lt;a href=&quot;/wiki/The_Troubles&quot; title=&quot;The Troubles&quot;&gt;The Troubles&lt;/a&gt;: The &lt;a href=&quot;/wiki/Provisional_Irish_Republican_Army&quot; title=&quot;Provisional Irish Republican Army&quot;&gt;Provisional Irish Republican Army&lt;/a&gt; engaged in &lt;b&gt;&lt;a href=&quot;/wiki/Attack_on_Derryard_checkpoint&quot; title=&quot;Attack on Derryard checkpoint&quot;&gt;a fierce firefight&lt;/a&gt;&lt;/b&gt; with the &lt;a href=&quot;/wiki/King%27s_Own_Scottish_Borderers&quot; title=&quot;King's Own Scottish Borderers&quot;&gt;King's Own Scottish Borderers&lt;/a&gt; at a vehicle checkpoint complex in &lt;a href=&quot;/wiki/County_Fermanagh&quot; title=&quot;County Fermanagh&quot;&gt;County Fermanagh&lt;/a&gt;, Northern Ireland.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/2006&quot; title=&quot;2006&quot;&gt;2006&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Baiji&quot; title=&quot;Baiji&quot;&gt;baiji&lt;/a&gt;&lt;/b&gt;, a &lt;a href=&quot;/wiki/River_dolphin&quot; title=&quot;River dolphin&quot;&gt;freshwater dolphin&lt;/a&gt; found only in the &lt;a href=&quot;/wiki/Yangtze_River&quot; class=&quot;mw-redirect&quot; title=&quot;Yangtze River&quot;&gt;Yangtze River&lt;/a&gt; in China, was announced as &lt;a href=&quot;/wiki/Functional_extinction&quot; title=&quot;Functional extinction&quot;&gt;functionally extinct&lt;/a&gt; by leaders of the &lt;a href=&quot;/wiki/Yangtze_Freshwater_Dolphin_Expedition_2006&quot; title=&quot;Yangtze Freshwater Dolphin Expedition 2006&quot;&gt;Yangtze Freshwater Dolphin Expedition&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_12&quot; title=&quot;December 12&quot;&gt;December 12&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 13, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161214000000/en</id>
		<title>On this day: December 14</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161214000000/en"/>
				<updated>2016-12-14T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Martyred_Intellectuals_Day&quot; title=&quot;Martyred Intellectuals Day&quot;&gt;Martyred Intellectuals Day&lt;/a&gt;&lt;/b&gt; in Bangladesh (&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt;); &lt;b&gt;&lt;a href=&quot;/wiki/Monkey_Day&quot; title=&quot;Monkey Day&quot;&gt;Monkey Day&lt;/a&gt;&lt;/b&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 120px;&quot;&gt;
&lt;a href=&quot;/wiki/File:At_the_South_Pole,_December_1911.jpg&quot; class=&quot;image&quot; title=&quot;Roald Amundsen and his team at the South Pole&quot;&gt;&lt;img alt=&quot;Roald Amundsen and his team at the South Pole&quot; src=&quot;//upload.wikimedia.org/wikipedia/en/thumb/1/1e/At_the_South_Pole%2C_December_1911.jpg/120px-At_the_South_Pole%2C_December_1911.jpg&quot; width=&quot;120&quot; height=&quot;80&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/en/thumb/1/1e/At_the_South_Pole%2C_December_1911.jpg/180px-At_the_South_Pole%2C_December_1911.jpg 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/1/1e/At_the_South_Pole%2C_December_1911.jpg/240px-At_the_South_Pole%2C_December_1911.jpg 2x&quot; data-file-width=&quot;484&quot; data-file-height=&quot;321&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Roald Amundsen and his team at the South Pole&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/835&quot; title=&quot;835&quot;&gt;835&lt;/a&gt; – In the &lt;b&gt;&lt;a href=&quot;/wiki/Sweet_Dew_Incident&quot; title=&quot;Sweet Dew Incident&quot;&gt;Sweet Dew Incident&lt;/a&gt;&lt;/b&gt;, &lt;a href=&quot;/wiki/Emperor_Wenzong_of_Tang&quot; title=&quot;Emperor Wenzong of Tang&quot;&gt;Emperor Wenzong&lt;/a&gt; of the &lt;a href=&quot;/wiki/Tang_dynasty&quot; title=&quot;Tang dynasty&quot;&gt;Tang dynasty&lt;/a&gt; conspired to kill the powerful &lt;a href=&quot;/wiki/Eunuch&quot; title=&quot;Eunuch&quot;&gt;eunuchs&lt;/a&gt; of the Tang court, but the plot was foiled.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1836&quot; title=&quot;1836&quot;&gt;1836&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Toledo_War&quot; title=&quot;Toledo War&quot;&gt;Toledo War&lt;/a&gt;&lt;/b&gt;, the mostly bloodless &lt;a href=&quot;/wiki/Boundary_dispute&quot; class=&quot;mw-redirect&quot; title=&quot;Boundary dispute&quot;&gt;boundary dispute&lt;/a&gt; between &lt;a href=&quot;/wiki/Ohio&quot; title=&quot;Ohio&quot;&gt;Ohio&lt;/a&gt; and the adjoining &lt;a href=&quot;/wiki/Michigan_Territory&quot; title=&quot;Michigan Territory&quot;&gt;Territory of Michigan&lt;/a&gt;, unofficially ended with a resolution passed by the controversial &quot;Frostbitten Convention&quot;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1911&quot; title=&quot;1911&quot;&gt;1911&lt;/a&gt; – Norwegian explorer &lt;a href=&quot;/wiki/Roald_Amundsen&quot; title=&quot;Roald Amundsen&quot;&gt;Roald Amundsen&lt;/a&gt; and his team became &lt;b&gt;&lt;a href=&quot;/wiki/Amundsen%27s_South_Pole_expedition&quot; title=&quot;Amundsen's South Pole expedition&quot;&gt;the first people to reach the South Pole&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(pictured)&lt;/i&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1960&quot; title=&quot;1960&quot;&gt;1960&lt;/a&gt; – &lt;a href=&quot;/wiki/Australia_national_cricket_team&quot; title=&quot;Australia national cricket team&quot;&gt;Australian cricketer&lt;/a&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Ian_Meckiff&quot; title=&quot;Ian Meckiff&quot;&gt;Ian Meckiff&lt;/a&gt;&lt;/b&gt; was &lt;a href=&quot;/wiki/Run_out&quot; title=&quot;Run out&quot;&gt;run out&lt;/a&gt; on the last day of the first &lt;a href=&quot;/wiki/Test_cricket&quot; title=&quot;Test cricket&quot;&gt;Test&lt;/a&gt; between Australia and the &lt;a href=&quot;/wiki/West_Indies_cricket_team&quot; title=&quot;West Indies cricket team&quot;&gt;West Indies&lt;/a&gt;, causing the first &lt;a href=&quot;/wiki/Tied_Test&quot; title=&quot;Tied Test&quot;&gt;tied Test&lt;/a&gt; in the &lt;a href=&quot;/wiki/History_of_cricket&quot; title=&quot;History of cricket&quot;&gt;history of cricket&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/2008&quot; title=&quot;2008&quot;&gt;2008&lt;/a&gt; – During a press conference in &lt;a href=&quot;/wiki/Baghdad&quot; title=&quot;Baghdad&quot;&gt;Baghdad&lt;/a&gt;, Iraqi journalist &lt;b&gt;&lt;a href=&quot;/wiki/Muntadhar_al-Zaidi&quot; title=&quot;Muntadhar al-Zaidi&quot;&gt;Muntadhar al-Zaidi&lt;/a&gt;&lt;/b&gt; infamously &lt;a href=&quot;/wiki/Shoeing&quot; class=&quot;mw-redirect&quot; title=&quot;Shoeing&quot;&gt;threw his shoes&lt;/a&gt; at &lt;a href=&quot;/wiki/President_of_the_United_States&quot; title=&quot;President of the United States&quot;&gt;U.S. President&lt;/a&gt; &lt;a href=&quot;/wiki/George_W._Bush&quot; title=&quot;George W. Bush&quot;&gt;George W. Bush&lt;/a&gt;, yelling that &quot;this is for the widows and orphans and all those &lt;a href=&quot;/wiki/Casualties_of_the_Iraq_War&quot; title=&quot;Casualties of the Iraq War&quot;&gt;killed in Iraq&lt;/a&gt;&quot;.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_13&quot; title=&quot;December 13&quot;&gt;December 13&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 14, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161215000000/en</id>
		<title>On this day: December 15</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161215000000/en"/>
				<updated>2016-12-15T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/b&gt;: &lt;b&gt;&lt;a href=&quot;/wiki/Koninkrijksdag&quot; title=&quot;Koninkrijksdag&quot;&gt;Kingdom Day&lt;/a&gt;&lt;/b&gt; in Aruba, Curaçao, the Netherlands, and Sint Maarten (&lt;a href=&quot;/wiki/1954&quot; title=&quot;1954&quot;&gt;1954&lt;/a&gt;); &lt;b&gt;&lt;a href=&quot;/wiki/Zamenhof_Day&quot; title=&quot;Zamenhof Day&quot;&gt;Zamenhof Day&lt;/a&gt;&lt;/b&gt; in &lt;a href=&quot;/wiki/Esperanto_culture&quot; title=&quot;Esperanto culture&quot;&gt;Esperanto culture&lt;/a&gt;
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 100px;&quot;&gt;
&lt;a href=&quot;/wiki/File:Wanyan_Digunai_cropped.jpg&quot; class=&quot;image&quot; title=&quot;Emperor Hailingwang of Jin&quot;&gt;&lt;img alt=&quot;Emperor Hailingwang of Jin&quot; src=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Wanyan_Digunai_cropped.jpg/100px-Wanyan_Digunai_cropped.jpg&quot; width=&quot;100&quot; height=&quot;165&quot; srcset=&quot;//upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Wanyan_Digunai_cropped.jpg/150px-Wanyan_Digunai_cropped.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Wanyan_Digunai_cropped.jpg/200px-Wanyan_Digunai_cropped.jpg 2x&quot; data-file-width=&quot;680&quot; data-file-height=&quot;1124&quot; /&gt;&lt;/a&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;Emperor Hailingwang of Jin&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1161&quot; title=&quot;1161&quot;&gt;1161&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Wanyan_Liang&quot; title=&quot;Wanyan Liang&quot;&gt;Emperor Hailing&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(bust pictured)&lt;/i&gt; of the &lt;a href=&quot;/wiki/Jin_dynasty_(1115%E2%80%931234)&quot; title=&quot;Jin dynasty (1115–1234)&quot;&gt;Jin dynasty&lt;/a&gt; was assassinated in a military camp near the &lt;a href=&quot;/wiki/Yangtze_River&quot; class=&quot;mw-redirect&quot; title=&quot;Yangtze River&quot;&gt;Yangtze River&lt;/a&gt; front following Jin losses in the &lt;a href=&quot;/wiki/Battle_of_Caishi&quot; title=&quot;Battle of Caishi&quot;&gt;Battle of Caishi&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1791&quot; title=&quot;1791&quot;&gt;1791&lt;/a&gt; – The first ten &lt;a href=&quot;/wiki/Constitutional_amendment&quot; title=&quot;Constitutional amendment&quot;&gt;amendments&lt;/a&gt; to the &lt;a href=&quot;/wiki/United_States_Constitution&quot; title=&quot;United States Constitution&quot;&gt;United States Constitution&lt;/a&gt;, collectively known as the &lt;b&gt;&lt;a href=&quot;/wiki/United_States_Bill_of_Rights&quot; title=&quot;United States Bill of Rights&quot;&gt;Bill of Rights&lt;/a&gt;&lt;/b&gt;, were ratified.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1906&quot; title=&quot;1906&quot;&gt;1906&lt;/a&gt; – The &lt;b&gt;&lt;a href=&quot;/wiki/Great_Northern,_Piccadilly_and_Brompton_Railway&quot; title=&quot;Great Northern, Piccadilly and Brompton Railway&quot;&gt;Great Northern, Piccadilly and Brompton Railway&lt;/a&gt;&lt;/b&gt;, a 14.17-kilometre (8.80&amp;#160;mi) long deep-level underground tube railway connecting &lt;a href=&quot;/wiki/Hammersmith&quot; title=&quot;Hammersmith&quot;&gt;Hammersmith&lt;/a&gt; and &lt;a href=&quot;/wiki/Finsbury_Park,_London&quot; title=&quot;Finsbury Park, London&quot;&gt;Finsbury Park, London&lt;/a&gt;, opened.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1946&quot; title=&quot;1946&quot;&gt;1946&lt;/a&gt; – US-backed Iranian troops brought an end to the &lt;b&gt;&lt;a href=&quot;/wiki/Iran_crisis_of_1946&quot; title=&quot;Iran crisis of 1946&quot;&gt;Iran crisis&lt;/a&gt;&lt;/b&gt; when they marched upon the breakaway &lt;a href=&quot;/wiki/Republic_of_Mahabad&quot; title=&quot;Republic of Mahabad&quot;&gt;Republic of Mahabad&lt;/a&gt; and recaptured the territory.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1961&quot; title=&quot;1961&quot;&gt;1961&lt;/a&gt; – Former Nazi leader &lt;b&gt;&lt;a href=&quot;/wiki/Adolf_Eichmann&quot; title=&quot;Adolf Eichmann&quot;&gt;Adolf Eichmann&lt;/a&gt;&lt;/b&gt; was sentenced to death after being found guilty on fifteen criminal charges, including &lt;a href=&quot;/wiki/War_crime&quot; title=&quot;War crime&quot;&gt;war crimes&lt;/a&gt; and &lt;a href=&quot;/wiki/Crime_against_humanity&quot; class=&quot;mw-redirect&quot; title=&quot;Crime against humanity&quot;&gt;crimes against humanity&lt;/a&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_14&quot; title=&quot;December 14&quot;&gt;December 14&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 15, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	<entry>
		<id>https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161216000000/en</id>
		<title>On this day: December 16</title>
		<link rel="alternate" type="text/html" href="https://en.wikipedia.org/wiki/Special:FeedItem/onthisday/20161216000000/en"/>
				<updated>2016-12-16T00:00:00Z</updated>
		
		<summary type="html">&lt;p&gt;&lt;b&gt;&lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/b&gt;: &lt;a href=&quot;/wiki/National_Day&quot; title=&quot;National Day&quot;&gt;National Day&lt;/a&gt; in &lt;b&gt;&lt;a href=&quot;/wiki/Bahrain&quot; title=&quot;Bahrain&quot;&gt;Bahrain&lt;/a&gt;&lt;/b&gt;; &lt;a href=&quot;/wiki/Victory_Day&quot; title=&quot;Victory Day&quot;&gt;Victory Day&lt;/a&gt; in &lt;b&gt;&lt;a href=&quot;/wiki/Victory_day_of_Bangladesh&quot; title=&quot;Victory day of Bangladesh&quot;&gt;Bangladesh&lt;/a&gt;&lt;/b&gt; and &lt;b&gt;&lt;a href=&quot;/wiki/Vijay_Diwas_(India)&quot; title=&quot;Vijay Diwas (India)&quot;&gt;India&lt;/a&gt;&lt;/b&gt; (&lt;a href=&quot;/wiki/1971&quot; title=&quot;1971&quot;&gt;1971&lt;/a&gt;); &lt;b&gt;&lt;a href=&quot;/wiki/Day_of_Reconciliation&quot; title=&quot;Day of Reconciliation&quot;&gt;Day of Reconciliation&lt;/a&gt;&lt;/b&gt; in South Africa
&lt;/p&gt;
&lt;div style=&quot;float:right;margin-left:0.5em;&quot; id=&quot;mp-otd-img&quot;&gt;
&lt;div class=&quot;thumbinner mp-thumb&quot; style=&quot;background: transparent; border: none; padding: 0; max-width: 120px;&quot;&gt;
&lt;div class=&quot;mediaContainer&quot; style=&quot;width:120px&quot;&gt;&lt;audio id=&quot;mwe_player_0&quot; controls=&quot;&quot; preload=&quot;none&quot; style=&quot;width:120px&quot; class=&quot;kskin&quot; data-durationhint=&quot;604.536&quot; data-startoffset=&quot;0&quot; data-mwtitle=&quot;Antonin_Dvorak_-_symphony_no._9_in_e_minor_'from_the_new_world',_op._95_-_i._adagio_-_allegro_molto.ogg&quot; data-mwprovider=&quot;wikimediacommons&quot;&gt;&lt;source src=&quot;//upload.wikimedia.org/wikipedia/commons/5/5c/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_i._adagio_-_allegro_molto.ogg&quot; type=&quot;audio/ogg; codecs=&amp;quot;vorbis&amp;quot;&quot; data-title=&quot;Original Ogg file (176 kbps)&quot; data-shorttitle=&quot;Ogg source&quot; data-width=&quot;0&quot; data-height=&quot;0&quot; data-bandwidth=&quot;175824&quot;/&gt;&lt;/audio&gt;&lt;/div&gt;&lt;div class=&quot;thumbcaption&quot; style=&quot;padding: 0.25em 0; word-wrap: break-word;&quot;&gt;New World Symphony, 1st movement&lt;/div&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/1761&quot; title=&quot;1761&quot;&gt;1761&lt;/a&gt; – &lt;a href=&quot;/wiki/Seven_Years%27_War&quot; title=&quot;Seven Years' War&quot;&gt;Seven Years' War&lt;/a&gt;: Russian forces captured &lt;a href=&quot;/wiki/Ko%C5%82obrzeg&quot; title=&quot;Kołobrzeg&quot;&gt;Kolberg&lt;/a&gt;, Prussia's last port on the &lt;a href=&quot;/wiki/Baltic_Sea&quot; title=&quot;Baltic Sea&quot;&gt;Baltic coast&lt;/a&gt;, after a &lt;b&gt;&lt;a href=&quot;/wiki/Siege_of_Kolberg_(Seven_Years%27_War)&quot; title=&quot;Siege of Kolberg (Seven Years' War)&quot;&gt;four-month siege&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1811&quot; title=&quot;1811&quot;&gt;1811&lt;/a&gt; – The first two in a &lt;b&gt;&lt;a href=&quot;/wiki/1811%E2%80%9312_New_Madrid_earthquakes&quot; title=&quot;1811–12 New Madrid earthquakes&quot;&gt;series of four severe earthquakes&lt;/a&gt;&lt;/b&gt; struck the &lt;a href=&quot;/wiki/Midwestern_United_States&quot; title=&quot;Midwestern United States&quot;&gt;Midwestern United States&lt;/a&gt; and made the &lt;a href=&quot;/wiki/Mississippi_River&quot; title=&quot;Mississippi River&quot;&gt;Mississippi River&lt;/a&gt; appear to run backward.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1893&quot; title=&quot;1893&quot;&gt;1893&lt;/a&gt; – Czech composer &lt;a href=&quot;/wiki/Anton%C3%ADn_Dvo%C5%99%C3%A1k&quot; title=&quot;Antonín Dvořák&quot;&gt;Antonín Dvořák&lt;/a&gt;'s &lt;b&gt;&lt;a href=&quot;/wiki/Symphony_No._9_(Dvo%C5%99%C3%A1k)&quot; title=&quot;Symphony No. 9 (Dvořák)&quot;&gt;New World Symphony&lt;/a&gt;&lt;/b&gt; &lt;i&gt;(audio featured)&lt;/i&gt; premiered at &lt;a href=&quot;/wiki/Carnegie_Hall&quot; title=&quot;Carnegie Hall&quot;&gt;Carnegie Hall&lt;/a&gt; in &lt;a href=&quot;/wiki/New_York_City&quot; title=&quot;New York City&quot;&gt;New York City&lt;/a&gt;.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1930&quot; title=&quot;1930&quot;&gt;1930&lt;/a&gt; – &lt;b&gt;&lt;a href=&quot;/wiki/Herman_Lamm&quot; title=&quot;Herman Lamm&quot;&gt;Herman Lamm&lt;/a&gt;&lt;/b&gt;, &quot;the father of modern &lt;a href=&quot;/wiki/Bank_robbery&quot; title=&quot;Bank robbery&quot;&gt;bank robbery&lt;/a&gt;&quot;, killed himself during a botched robbery attempt in &lt;a href=&quot;/wiki/Clinton,_Indiana&quot; title=&quot;Clinton, Indiana&quot;&gt;Clinton, Indiana&lt;/a&gt;, US, rather than be captured by police.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1938&quot; title=&quot;1938&quot;&gt;1938&lt;/a&gt; – &lt;a href=&quot;/wiki/Adolf_Hitler&quot; title=&quot;Adolf Hitler&quot;&gt;Adolf Hitler&lt;/a&gt; instituted the &lt;b&gt;&lt;a href=&quot;/wiki/Cross_of_Honour_of_the_German_Mother&quot; title=&quot;Cross of Honour of the German Mother&quot;&gt;Cross of Honour of the German Mother&lt;/a&gt;&lt;/b&gt; as an &lt;a href=&quot;/wiki/Order_of_merit&quot; title=&quot;Order of merit&quot;&gt;order of merit&lt;/a&gt; for &lt;a href=&quot;/wiki/Imperial_Germans&quot; title=&quot;Imperial Germans&quot;&gt;Imperial German&lt;/a&gt; women.&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/1986&quot; title=&quot;1986&quot;&gt;1986&lt;/a&gt; – &lt;a href=&quot;/wiki/Dinmukhamed_Konayev&quot; class=&quot;mw-redirect&quot; title=&quot;Dinmukhamed Konayev&quot;&gt;Dinmukhamed Konayev&lt;/a&gt; was dismissed from the post of First Secretary of the &lt;a href=&quot;/wiki/Communist_Party_of_Kazakhstan&quot; title=&quot;Communist Party of Kazakhstan&quot;&gt;Communist Party of Kazakhstan&lt;/a&gt;, sparking &lt;b&gt;&lt;a href=&quot;/wiki/Jeltoqsan&quot; title=&quot;Jeltoqsan&quot;&gt;riots throughout the country&lt;/a&gt;&lt;/b&gt;.&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;margin-top: 0.5em;&quot;&gt;
More anniversaries: &lt;div class=&quot;hlist inline nowraplinks&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;a href=&quot;/wiki/December_15&quot; title=&quot;December 15&quot;&gt;December 15&lt;/a&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/December_16&quot; title=&quot;December 16&quot;&gt;December 16&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;a href=&quot;/wiki/December_17&quot; title=&quot;December 17&quot;&gt;December 17&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
&lt;div class=&quot;otd-footer hlist noprint&quot; style=&quot;text-align: right;&quot;&gt;
&lt;ul&gt;&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/Wikipedia:Selected_anniversaries/December&quot; title=&quot;Wikipedia:Selected anniversaries/December&quot;&gt;Archive&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;https://lists.wikimedia.org/mailman/listinfo/daily-article-l&quot; class=&quot;extiw&quot; title=&quot;mail:daily-article-l&quot;&gt;By email&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt; &lt;b&gt;&lt;a href=&quot;/wiki/List_of_historical_anniversaries&quot; title=&quot;List of historical anniversaries&quot;&gt;List of historical anniversaries&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;div style=&quot;font-size: smaller;&quot;&gt;
&lt;ul&gt;&lt;li&gt; Current date: &lt;span class=&quot;nowrap&quot;&gt;December 16, 2016&lt;/span&gt; (&lt;a href=&quot;/wiki/Coordinated_Universal_Time&quot; title=&quot;Coordinated Universal Time&quot;&gt;UTC&lt;/a&gt;)&lt;/li&gt;
&lt;li&gt; &lt;span class=&quot;plainlinks&quot; id=&quot;otd-purgelink&quot;&gt;&lt;span class=&quot;nowrap&quot;&gt;&lt;a class=&quot;external text&quot; href=&quot;//en.wikipedia.org/w/index.php?title=MediaWiki:Ffeed-onthisday-transcludeme&amp;amp;action=purge&quot;&gt;Reload this page&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;
</summary>
			</entry>

	</feed>